Update main.yml
Update yaml in Main Branch

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,6 @@
 name: CI Pipeline Hanoi Towers
 
 on:
-  push:
-    branches:
-      - master
   pull_request:
     types: [opened, synchronize, reopened]
 
@@ -18,7 +15,7 @@ jobs:
       HANOI_FRONTEND_URL: ${{ vars.HANOI_FRONTEND_URL }}
       HANOI_BACKEND_URL: ${{ vars.HANOI_BACKEND_URL }}
     steps:
-     - name: Checkout
+     - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Set up .env files
        run: |
@@ -52,14 +49,19 @@ jobs:
      - name: Install needed Chrome Version
        run: npm install -g chromedriver@125
      - name: Run Axe with set Chromedriver path
-       run: axe http://localhost:8080, http://localhost:8080/game, http://localhost:8080/cheat, http://localhost:8080/solver --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver --exit
+       continue-on-error: true
+       run: axe http://localhost:8080, http://localhost:8080/game, http://localhost:8080/cheat, http://localhost:8080/solver --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver --exit >> results
      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
-       env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       uses: JoseThen/comment-pr@v1.2.0
+       with:
+         file_path: './results'
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+     - name: Fail if results file exists
        run: |
-          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
-          curl -s -H "Authorization: token $GITHUB_TOKEN" \
-          -X POST \
-          -d "{\"body\": \"Thank you for your contribution! We are reviewing your pull request.\"}" \
-          "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/comments"
+         if [ -f "./results" ]; then
+           echo "Results file with accessibility issues exists - Details in PR-comment. Failing the workflow."
+           exit 1
+         else
+           echo "No errors, be sure to still check manually for accessibility ;)"
+         fi
